language: cpp

script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
- cmake --build _build --target install

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      
      - cmake-data
      
before_install:
  - pip install --user cpp-coveralls
  
after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
